In [1]:
import numpy as np

### 9.1 認識Numpy陣列

#### 第1題

In [2]:
#(a)
arr=np.array([[1.2],[4.3],[5.4],[6.7]])
print(arr)
print(f'shape={arr.shape}')
print(f'ndim={arr.ndim}')
print(f'size={arr.size}')

[[1.2]
 [4.3]
 [5.4]
 [6.7]]
shape=(4, 1)
ndim=2
size=4


In [3]:
#(b)
arr=np.array([[1.2,4.3,5.4,6.7]])
print(arr)
print(f'shape={arr.shape}')
print(f'ndim={arr.ndim}')
print(f'size={arr.size}')

[[1.2 4.3 5.4 6.7]]
shape=(1, 4)
ndim=2
size=4


In [4]:
#(c)
a=np.array([[5]])
print(a)
print(f'shape={a.shape}')
print(f'ndim={a.ndim}')
print(f'size={a.size}')

[[5]]
shape=(1, 1)
ndim=2
size=1


In [5]:
#(d)
arr=np.array([[4,4,4,4],[2,2,2,2],[5,5,5,5]])
print(arr)
print(f'shape={arr.shape}')
print(f'ndim={arr.ndim}')
print(f'size={arr.size}')

[[4 4 4 4]
 [2 2 2 2]
 [5 5 5 5]]
shape=(3, 4)
ndim=2
size=12


#### 第3題

In [6]:
arr=np.array([[[0,0,0,0],
               [0,0,0,0],
               [0,0,0,0]],
              [[1,1,1,1],
               [1,1,1,1],
               [1,1,1,1]]])
print(arr)
print(f'shape={arr.shape}')

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
shape=(2, 3, 4)


In [7]:
print(arr[0])
print(arr[1])

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


#### 第5題

In [8]:
np.arange(0,1.001,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

#### 第7題

In [9]:
np.random.rand(2,3)*2-1

array([[ 0.13901452,  0.98906304, -0.46385893],
       [-0.42995787, -0.80092234, -0.88792577]])

#### 第9題

In [10]:
a=np.array([[ 0, 1, 3, 4, 5],
            [ 6, 7, 8, 9,10],
            [11,12,13,14,15]])
rg=np.random.default_rng(999)

In [11]:
#(a)
rg.choice(a.flatten(),8,replace=False)

array([ 1, 10, 11,  7,  3, 14, 12,  8])

In [12]:
#(b)
rg.choice(a.flatten(),10,replace=True)

array([10,  9, 14,  9,  3,  0,  9, 15, 10,  5])

In [13]:
#(c)
rg.choice(a,2,replace=False,axis=0)

array([[ 6,  7,  8,  9, 10],
       [ 0,  1,  3,  4,  5]])

In [14]:
#(d)
rg.permutation(a,axis=1)

array([[ 4,  1,  3,  5,  0],
       [ 9,  7,  8, 10,  6],
       [14, 12, 13, 15, 11]])

### 9.2 陣列元素的提取

#### 第11題

In [15]:
a=np.arange(20).reshape((4,5))
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [16]:
#(a)
a[0:3,1:4]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [17]:
#(b)
a[:,[2,4]]

array([[ 2,  4],
       [ 7,  9],
       [12, 14],
       [17, 19]])

In [18]:
#(c)
a[1:4,:]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [19]:
#(d)
a[:,::-1]

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10],
       [19, 18, 17, 16, 15]])

In [20]:
#(e)
a[a%3==0]

array([ 0,  3,  6,  9, 12, 15, 18])

In [21]:
#(f)
[a[r,c] for r in range(a.shape[0]) for c in range(a.shape[1]) if (r+c)%2==0]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [22]:
#(g)
a[np.logical_and(a%2==0 , a%3!=0)].size

6

#### 第13題

In [23]:
a=np.arange(10,30).reshape(4,5)
a

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [24]:
#(a)
a[[1,2],[2,3]]

array([17, 23])

In [25]:
#(b)
a[[0,1,2],[0,1,3]]

array([10, 16, 23])

In [26]:
#(c)
a[[0,2,3],3:5]

array([[13, 14],
       [23, 24],
       [28, 29]])

In [27]:
#(d)
a[2:4,[0,2,3]]

array([[20, 22, 23],
       [25, 27, 28]])

In [28]:
#(e)
a[0:3:2,0:3:2]

array([[10, 12],
       [20, 22]])

In [29]:
#(f)
a[0:2,[1,3,4]]

array([[11, 13, 14],
       [16, 18, 19]])

### 9.3 陣列的進階處理

#### 第15題

In [30]:
a=np.arange(12)

In [31]:
#(a)
print(a)
print(f'size={a.size}')
print(f'shape={a.shape}')
print(f'ndim={a.ndim}')


[ 0  1  2  3  4  5  6  7  8  9 10 11]
size=12
shape=(12,)
ndim=1


In [32]:
#(b)
a.reshape(4,3),a.reshape(1,12),a.reshape(12,1),a.reshape(2,2,3)

(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]]),
 array([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11]]),
 array([[[ 0,  1,  2],
         [ 3,  4,  5]],
 
        [[ 6,  7,  8],
         [ 9, 10, 11]]]))

#### 第17題

In [33]:
a=np.arange(24).reshape(2,3,4)

In [34]:
#(a)
a[None,:,:,:]

array([[[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]])

In [35]:
#(b), 同 a.T
np.swapaxes(a,0,2)

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [36]:
a.T

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [37]:
#(c),移動之後，軸0的方向變成有4個元素了
np.moveaxis(a,2,0)

array([[[ 0,  4,  8],
        [12, 16, 20]],

       [[ 1,  5,  9],
        [13, 17, 21]],

       [[ 2,  6, 10],
        [14, 18, 22]],

       [[ 3,  7, 11],
        [15, 19, 23]]])

In [38]:
#(d)
np.split(a,2,axis=0)

[array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]]),
 array([[[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])]

In [39]:
#(e)
np.split(a,2,axis=2)

[array([[[ 0,  1],
         [ 4,  5],
         [ 8,  9]],
 
        [[12, 13],
         [16, 17],
         [20, 21]]]),
 array([[[ 2,  3],
         [ 6,  7],
         [10, 11]],
 
        [[14, 15],
         [18, 19],
         [22, 23]]])]

In [40]:
#(e)
np.vstack((a[0],a[1]))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [41]:
np.hstack((a[0],a[1]))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])