In [1]:
import numpy as np

### 10.1 基本運算

#### 第1題

In [2]:
a=np.array([67.4, 76.1, 73.7, 84.9])

In [3]:
#(a)
np.sqrt(a)

array([8.2097503 , 8.7235314 , 8.58487041, 9.2141196 ])

In [4]:
#(b)
np.modf(a)[0]

array([0.4, 0.1, 0.7, 0.9])

In [5]:
#(c)
a[np.floor(a)%2==0]

array([76.1, 84.9])

In [6]:
#(d)
np.argmin(a)

0

In [7]:
#(e)
a[a>60].mean()

75.525

#### 第3題

In [8]:
a=np.array([[12, 10,  0,  9, 12],
            [ 3, 17, 18, -3,  3],
            [ 0,  7,  8,  5,  0]])

In [9]:
#(a)
np.max(a,axis=1)

array([12, 18,  8])

In [10]:
#(b)
np.argmin(a,axis=0)

array([2, 2, 0, 1, 2], dtype=int64)

In [11]:
#(c)
np.sum(a,axis=1)

array([43, 38, 20])

In [12]:
#(d)
np.mean(a,axis=0)

array([ 5.        , 11.33333333,  8.66666667,  3.66666667,  5.        ])

In [13]:
#(e)
np.where(a==0)

(array([0, 2, 2], dtype=int64), array([2, 0, 4], dtype=int64))

In [14]:
#(f)
a[a>0].sum()

104

In [15]:
#(g)
np.where(a==a.max())

(array([1], dtype=int64), array([2], dtype=int64))

In [16]:
#(h)
a[:,np.all(a!=0,axis=0)]

array([[10,  9],
       [17, -3],
       [ 7,  5]])

In [17]:
#(i)
np.unique(a,axis=1)

array([[ 0,  9, 10, 12],
       [18, -3, 17,  3],
       [ 8,  5,  7,  0]])

In [18]:
#(j-1)
a[np.all(a!=5,axis=1),:]

array([[12, 10,  0,  9, 12],
       [ 3, 17, 18, -3,  3]])

In [19]:
#(j-2)
a[:,np.all(a!=5,axis=0)]

array([[12, 10,  0, 12],
       [ 3, 17, 18,  3],
       [ 0,  7,  8,  0]])

In [20]:
#(k)
a[np.abs(a)==3].size

3

#### 第5題

In [21]:
a=np.array([[0,1,2,3,4],
            [2,3,4,1,0],
            [4,0,1,2,3],
            [1,2,3,4,0],
            [3,4,0,1,2]])

In [22]:
#(a)
r,c=2,2
row,col=np.where(a==4)
pos=np.argmin((row-r)**2+(col-c)**2)
row[pos],col[pos]

(1, 2)

In [23]:
#(b)
r,c=4,3
row,col=np.where(a==0)
pos=np.argmin((row-r)**2+(col-c)**2)
row[pos],col[pos]

(4, 2)

In [24]:
#(c)
r,c=4,0
row,col=np.where(a==2)
pos=np.argmin((row-r)**2+(col-c)**2)
row[pos],col[pos]

(3, 1)

In [25]:
#(d)
row,col=np.where(a==4)
pts=np.vstack((row,col))
n=pts.shape[1]
dist=np.zeros((n,n))
for i in range(n):
    for j in range(i+1,n):
        dist[i,j]=((pts[:,i]-pts[:,j])**2).sum()  # sum of squared distance btw points i and j
pos=np.where(dist==np.max(dist))
print(f'point 1: ({pts[0,pos[0]][0]}, {pts[1,pos[0]][0]})') 
print(f'point 2: ({pts[0,pos[1]][0]}, {pts[1,pos[1]][0]})') 

point 1: (0, 4)
point 2: (4, 1)


In [26]:
#(e)
(a==0).sum()

5

#### 第7題

In [27]:
def find_pi(n):
    k=np.arange(0,n)
    return (1/16**k*(4/(8*k+1)-2/(8*k+4)-1/(8*k+5)-1/(8*k+6))).sum()

In [28]:
find_pi(2)

3.1414224664224664

In [29]:
find_pi(10)

C:\Users\wienh\AppData\Local\Temp\ipykernel_9912\2526062004.py:3: RuntimeWarning: divide by zero encountered in true_divide
  return (1/16**k*(4/(8*k+1)-2/(8*k+4)-1/(8*k+5)-1/(8*k+6))).sum()


inf

In [30]:
np.pi

3.141592653589793

### 10.2 資料排序

#### 第9題

In [31]:
pts=np.array([[6,7,7,3,6],
              [4,1,4,8,9]])
np.argsort(np.sum(pts**2,axis=0))

array([1, 0, 2, 3, 4], dtype=int64)

### 10.3 數學矩陣的相關運算

#### 第11題

In [32]:
import numpy.linalg as la

In [33]:
#(a)
m=np.array([[-1,2],[1,6]])
b=np.array([[4],[6]])
la.solve(m,b)

array([[-1.5 ],
       [ 1.25]])

In [34]:
#(b)
m=np.array([[3,2,4],[5,7,3],[1,6,0]])
b=np.array([[-6,2,1]]).T
la.solve(m,b)

array([[ 3.04545455],
       [-0.34090909],
       [-3.61363636]])

In [35]:
#(c)
m=np.array([[0,2,-2],[7,4,3],[8,-4,-5]])
b=np.array([[17,12,16]]).T
la.solve(m,b)

array([[ 1.27731092],
       [ 4.07983193],
       [-4.42016807]])

### 10.4 廣播運算

#### 第13題

In [36]:
a=np.array([78,22,65,87,12,98,63,79])
x=57

In [37]:
# using for loop
diff=np.inf
for n in a:
    if abs(x-n)<diff:
        diff=abs(x-n)
        result=n
result

63

In [38]:
# without for loop
a[np.argmin(abs(a-x))]

63

#### 第15題

In [39]:
a=np.array([[3,4,8,3,8,9,7],
            [8,3,5,0,3,2,3],
            [9,2,4,4,3,6,2]])
b=np.array([[8,7,3,1],
            [5,4,4,2],
            [4,9,0,6]])

In [40]:
#(a)
D=np.zeros((a.shape[1],b.shape[1]))
for r in range(a.shape[1]):
    for c in range(b.shape[1]):
        D[r,c]=np.sum((a[:,r]-b[:,c])**2)
D

array([[59., 32., 97., 49.],
       [24., 59.,  6., 26.],
       [ 0., 27., 42., 62.],
       [50., 57., 32., 12.],
       [ 5., 38., 35., 59.],
       [14., 17., 76., 64.],
       [ 9., 50., 21., 53.]])

In [41]:
D

array([[59., 32., 97., 49.],
       [24., 59.,  6., 26.],
       [ 0., 27., 42., 62.],
       [50., 57., 32., 12.],
       [ 5., 38., 35., 59.],
       [14., 17., 76., 64.],
       [ 9., 50., 21., 53.]])

In [42]:
#(b)
print(a[:,:,None].shape)
print(b[:,None,:].shape)

(3, 7, 1)
(3, 1, 4)


In [43]:
np.sum((a[:,:,None]-b[:,None,:])**2,axis=0)

array([[59, 32, 97, 49],
       [24, 59,  6, 26],
       [ 0, 27, 42, 62],
       [50, 57, 32, 12],
       [ 5, 38, 35, 59],
       [14, 17, 76, 64],
       [ 9, 50, 21, 53]], dtype=int32)

In [44]:
#(c)
print(a[:,None,:].shape)
print(b[:,:,None].shape)

(3, 1, 7)
(3, 4, 1)


In [45]:
np.sum((a[:,None,:]-b[:,:,None])**2,axis=0)

array([[59, 24,  0, 50,  5, 14,  9],
       [32, 59, 27, 57, 38, 17, 50],
       [97,  6, 42, 32, 35, 76, 21],
       [49, 26, 62, 12, 59, 64, 53]], dtype=int32)

### 10.5 儲存Numpy陣列

#### 第17題

In [46]:
a=np.array([1,4,5,7,8])

In [47]:
#(a)
z=a.tobytes()

In [48]:
#(b)
np.frombuffer(z,dtype=int)

array([1, 4, 5, 7, 8])

In [49]:
#(c)
np.save('example.npy',a)
np.load('example.npy')

array([1, 4, 5, 7, 8])